### ISSUE TITLE
Exception Unable to find design file CustomerFormDesign.html in my.vaadin.app

### ISSUE THREAD

**Issue by ilmarmors** [vaadin/tutorial#1]
Fixing typo mistake and renaming java/my/vaaadin/app to java/my/vaadin/app introduced exception when running app:

com.vaadin.ui.declarative.DesignException: Unable to find design file CustomerFormDesign.html in my.vaadin.app 

It happens because resources/my/vaaadin/app wasn't renamed to resources/my/vaadin/app.

And MyUI.java need to fix typo in Widgetset refernce too
-@Widgetset("my.vaaadin.app.MyAppWidgetset")
+@Widgetset("my.vaadin.app.MyAppWidgetset")

**Comment by mstahv** [comment]
Thanks for the heads up, you shouldn't let a dude with a typo fix his own typos :-)
