### ISSUE TITLE
Vaadin 7 or 8 ?

### ISSUE THREAD

**Issue by SQL-data** [vaadin/tutorial#5]
Hello Alejandro,

https://www.useloom.com/share/00d0efd5f9a048d5a86bc4fb1629a432

I have spent the last week viewing your wonderful Vaadin 7 tutorial:
https://vaadin.com/docs7/-/part7/framework/tutorial.html

Is the information here on Github for Vaadin 7 or Vaadin 8?

As I was not able to get the beginning tutorial to work in Vaadin 7, so I am hoping to try again today, following the instructions that are given here on Github -- by downloading the source and hope I can successfully complete the beginners tutorial.

Thank you.

https://vaadin.com/forum#!/thread/15496153

Jon

**Comment by alejandro-du** [comment]
Hi,

The example is available for both Vaadin 7 and 8. [Master branch](https://github.com/vaadin/tutorial/) is for 8 and [v7 branch](https://github.com/vaadin/tutorial/tree/v7) is for 7.

**Comment by dataSQL** [comment]
Thank you!
